title: Sharifah Nurulhuda Alhabsyi
logo: assets/img/profile_2.png
description: Data Science Enthusiast | Python | Deep Learning | Experienced Educator
# show_downloads: true
theme: jekyll-theme-architect
