title: <img src="assets/img/hello.png">
logo: assets/img/profile_3.jpeg
description:  Python | Basic SQL | Deep Learning | Data Science Enthusiast | Educator
# show_downloads: true
theme: jekyll-theme-minimal
